apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cv-parser-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cv-parser
  # start with 8 pods instead of 2
  minReplicas: 6
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # scale when average CPU > 20% (instead of 50%)
        averageUtilization: 20
